name: driver-action
on: [push]
jobs:
        run-driver:
                name: Run Driver
                runs-on: ubuntu-latest
                steps:
                        - name: Download Repository
                          uses: actions/checkout@v2

                        - name: Make the Driver
                          run: make

                        - name: Run the Driver
                          run: java -jar build/SortingAlgorithms.jar
